#!/bin/sh -e

GREEN='\033[1;32m'
RED='\033[1;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

SYSTEM=$(uname -m)

case "$SYSTEM" in
    x86_64)
        FLAKE_TARGET="x86_64-linux"
        ;;
    aarch64)
        FLAKE_TARGET="aarch64-linux"
        ;;
    *)
        echo "${RED}Unsupported architecture: $SYSTEM${NC}"
        exit 1
        ;;
esac

is_nix_os() {
    [ -e /etc/NIXOS ] && return 0

    return 1
}

echo "${YELLOW}Starting build...${NC}"

nixpkgs_date=$(nix flake metadata | grep -A1 'nixpkgs:' | grep '202' | awk '{print $NF}')
echo "nixpkgs input last updated: $nixpkgs_date"

if [ "$(date -d "$nixpkgs_date" +%s)" -lt "$(date -d '90 days ago' +%s)" ]; then
    echo "⚠️  nixpkgs input is over 90 days old. Consider running:"
    echo "   nix flake update"
fi

if is_nix_os; then
    echo "Running on a NixOS-based system"
    /run/current-system/sw/bin/nixos-rebuild build --flake .#$FLAKE_TARGET "$@"
else
    echo "Running on a Linux system (non-NixOS)"
    nix --extra-experimental-features 'nix-command flakes' \
        build .#homeConfigurations.$FLAKE_TARGET.activationPackage "$@" \
        --show-trace
fi

echo "${GREEN}Build complete!${NC}"
